spring:
  application:
    name: notifaction-service
  kafka:
    bootstrap-servers:
    - localhost:9092      
    template:
      default-topic: productoCategoriaTopic
    consumer:
      key-deserializer: org.apache.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties: 
        "[spring.json.value.default.type]": event:com.ecommerce.notification.app.event.ProductoWithCategoria
      group-id: notification-id
    