server:
  port: 8082
spring:
  cloud:
    config:
      server: 
        git:
          default-label: kafka
          uri: https://github.com/kokyvr/microservice-ecommerce
          search-paths: config-data
          username: ${username}
          password: ${password}
  application:
    name: config-service        
          